######################################################################
# Automatically generated by qmake (3.0) mer. juin 18 12:47:04 2014
######################################################################

TEMPLATE = app
TARGET = mindWave
INCLUDEPATH += .

# Input
HEADERS += mindwave.hpp ThinkGearStreamParser.h
SOURCES += main.cpp mindwave.cpp ThinkGearStreamParser.c
